<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="8737" started-at="2019-07-05T17:55:17Z" finished-at="2019-07-05T17:55:26Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="8737" started-at="2019-07-05T17:55:17Z" finished-at="2019-07-05T17:55:26Z">
      <class name="tests.LoginTest">
        <test-method status="FAIL" signature="testUserIsAbleToLoginIntoApp()[pri:0, instance:tests.LoginTest@51565ec2]" name="testUserIsAbleToLoginIntoApp" duration-ms="8693" started-at="2019-07-05T20:55:17Z" finished-at="2019-07-05T20:55:26Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:Current URL after login should be 'https://www.saucedemo.com/inventory.html111', but fould [https://www.saucedemo.com/inventory.html] expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:Current URL after login should be 'https://www.saucedemo.com/inventory.html111', but fould [https://www.saucedemo.com/inventory.html] expected [true] but found [false]at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)at tests.LoginTest.testUserIsAbleToLoginIntoApp(LoginTest.java:40)at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- testUserIsAbleToLoginIntoApp -->
      </class> <!-- tests.LoginTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
